# Databricks notebook source
# MAGIC %sql
# MAGIC drop table development.dev_mpo_soil_curated.docs_text;

# COMMAND ----------

# DBTITLE 1,Create table to hold extracted pdf text
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS development.dev_mpo_soil_curated.docs_text ( id BIGINT GENERATED BY DEFAULT AS IDENTITY, text STRING ) tblproperties (delta.enableChangeDataFeed = true);

# COMMAND ----------

# DBTITLE 1,Create table to track which pdf files we've already processed
# MAGIC %sql
# MAGIC CREATE TABLE IF NOT EXISTS development.dev_mpo_soil_curated.docs_track (file_name STRING) tblproperties (delta.enableChangeDataFeed = true);